baseurl = "https://blog.jonhathanrodas.com/"
languageCode = "es"
title = "Jonhathan Rolando Rodas López - Blog"

# Copyright notice. This is displayer in the footer.
copyright = "© Jonhathan Rolando Rodas Lpez "



# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# Google Analytics API key.
googleAnalytics = "Your Google Analytics tracking id"

# enable get info from git commits, such as file modification time.
# so we don't have to manually update it.
enableGitInfo = true


theme= "pehtheme-hugo"
[params]
	mode="toggle"
	description = "Blog personal personal sobre Tecnología, Desarrollo de Software, Ciberseguridad y Ciencias Forenses."
	og_image= "cover.png"

	[author]
		name = "Jonathan Rolando Rodas López"
		bio = "Software Engineer and Blogger"
		location = "Guatemala, CA"
		website = "https://www.jonathanrodas.com"
		email = "me@jonathanrodas.com"
		avatar = "https://www.jonhathanrodas.com/_next/image?url=%2Fprofile.jpg&w=640&q=75"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/athul/archie"


# Main menu Items

[[menu.main]]
name = "Inicio"
url = "/"
weight = 1

[[menu.main]]
name = "Artículos"
url = "/posts/"
weight = 2

[[menu.main]]
name = "Categorías"
url = "/categories/"
weight = 3

[[menu.main]]
name = "Sobre mi"
url = "https://www.jonhathanrodas.com"
weight = 4

[services]
  [services.disqus]
    shortname = 'jonhathanrodas-com'

enableRobotsTXT = true


[imaging]
  bgColor = '#ffffff'
  hint = 'photo'
  quality = 75
  resampleFilter = 'box'


[markup.tableOfContents]
  endLevel = 3    # Hasta qué nivel de encabezado incluir (h1, h2, h3)
  ordered = false # Usar números en la lista (true) o puntos (false)
  startLevel = 2  # Desde qué nivel de encabezado empezar (h2)



