baseurl = "https://blog.jonhathanrodas.com/"
languageCode = "es"
title = "Jonhathan Rodas"

# Copyright notice. This is displayer in the footer.
copyright = "© Jonhathan Rolando Rodas Lopez"


# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# Google Analytics API key.
googleAnalytics = "Your Google Analytics tracking id"

# enable get info from git commits, such as file modification time.
# so we don't have to manually update it.
enableGitInfo = true


theme= "archie"
[params]
	mode="toggle"
	description = "Blog personal personal sobre Tecnología, Desarrollo de Software, Ciberseguridad y Ciencias Forenses."

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/athul/archie"


# Main menu Items

[[menu.main]]
name = "Inicio"
url = "/"
weight = 1

[[menu.main]]
name = "Artículos"
url = "/posts/"
weight = 2

[[menu.main]]
name = "Categorías"
url = "/tags/"
weight = 3

[[menu.main]]
name = "Sobre mi"
url = "https://www.jonhathanrodas.com"
weight = 4




